name: C/C++ CI

on:
  push:
    branches: [ master]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  
  linux-test:
    name: Linux test
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        git submodule init
        git submodule update
        make
    
    - name: build 
      run: |
        python3 phist.py ./example/virus ./example/host common_kmers.csv predictions.csv
        cmp common_kmers.csv ./example/common_kmers.csv
        cmp predictions.csv ./example/predictions.csv
        
         
  macos-build:
    name: macOS test
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        git submodule init
        git submodule update
        make

