name: C/C++ CI

on:
  push:
    branches: [ master]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  
  linux-test:
    name: Linux test
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        git submodule init
        git submodule update
        make
    
    - name: predict (out dir) 
      run: |
        python3 phist.py ./example/virus ./example/host ./out/
        diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines ./out/common_kmers.csv ./example/common_kmers.csv
        diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines ./out/predictions.csv ./example/predictions.csv
        
    - name: predict (out files) 
      run: |
        python3 phist.py ./example/virus ./example/host common_kmers.csv predictions.csv
        diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines common_kmers.csv ./example/common_kmers.csv
        diff -u --ignore-space-change --strip-trailing-cr --ignore-blank-lines predictions.csv ./example/predictions.csv    
        
         
  macos-build:
    name: macOS test
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        git submodule init
        git submodule update
        make

